path = File.expand_path('../', __FILE__)
require File.join(path, 'lib/MAService.rb')
require File.join(path, 'lib/JIMService.rb')
require File.join(path, 'lib/FuriganaService.rb')
require File.join(path, 'lib/KouseiService.rb')
require File.join(path, 'lib/DAService.rb')
require File.join(path, 'lib/KeyphraseService.rb')
require File.join(path, 'lib/OpenLocalPlatform.rb')
require File.join(path, 'lib/weather.rb')
require File.join(path, 'lib/placeinfo.rb')